sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '6'
cache:
- node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- codeclimate-test-reporter < coverage/lcov.info
- ckeditor5-dev-tests-save-revision
env:
  global:
  - secure: m2JBfEz/ciHTLEocBEqoyDJ+N2xeyaGHr/MdSj2iZtVHyfYGH2CkAgvYaoZpeb3p2JnMw26c73h6JGjgjIh2M97KPDF1cXTSRS/8XiifrjIU7fgzB5TNU1/X8Ce/4ZaF5zF539NRAVINIHYihPcNNMDH9LHj7vcqZ5V2KPY5NJe/SELj6PVj1F+uwyceVOFPd4TwtqYPyH+rjrLD/ULrtv/73+PMLhOpUffgSF5WlVk6M+mA96ynIfbr+8kxYar/m0DnVEuSq+/7dH50iekpgMcNYpQnVlm4+yfYAjvuMmt6nRQwwj/o6R+cV0+2yBGmWomFIb2FBS4y2DvmDbg/zHhUYNxoUkaV1Bft6Hi4FnVZueS5cPjB6Id3kJi0N0MGJMiHk2hqJ0CVGYemLO+dzSfsOz2B7Y85HqmljIdyG2FOgTerOpfk4t3MbybXsKT45q5Yto0AjSw4npZj90GKAITsHPTaC2WIPy5o59UhsIhCBQXmAHAtd0e3Y9lWwTotTGjhsPr1Lb/r5vu7plW+Eg4wWaP08ZMUE9DnrwVaLqo+bXG3F+A3N7SS2ngL7iQ3xuLI58X063ejFLSDjspkOwO+LSFZ4W79TJZtL3zTO2h1NWLAQ5OhNtAkjaHQNVEI3/zLp5J91dDjsIJTrIWA6TaL8r6ZpmDtTL+tvx3qAgY=
  - secure: g16gbgRU58hg4pPiGJiRizBEH87yqEJMZwDDxtARbvClqDwyzH2e6Z+NGg33UKJNQcvd0gi7ag1RgxB4q3VAKvA3XkFImoc0VVS1tvWf9hjR2ft5VYlhF4Ec8KW7Av8wVHCwDTzK5MitNH7b+7/lKl79nSey6aEptGTgScSgINKhNiPhHVifq9+BMnXEgBp67fFunhPHgNbBJL8NiwQvQmiy7ZEgacYGCGqmYOj+uTnNcfPppy5w8lPHrnS9s/HPfl1dnsi4StA3KagY/nQUsr+6msAjuzl+AMkRy29OnFHQDtEAjsTQrkBpg+OFbYNPStwPtFlMdVckqjXABvlBJQhC4lUbnVXly1tQe9yJ71KlZWQ9lTSdWtmgrzMonFVNa1thPiPseK4Jc2nNqCwuVJZDrSJxV2Eit6lMwjvQHDRS6Quvzf5CCT2B4MNkGcnS8DwYfF08d/s+59kq9bwQjYu9e3wnFTsYrxhSy4oQCJCXfPEYzfYFaPSX18Pz8kLfdm/nWFcpNQ+EOoTKoVtt2it6/F4zXrIPyF8BAdlQVAaNz+4raCqb3Sv+RPOLEQUztq84U+huwAVSQqUBrHz6l+ZNcLQ0ekpUPDJAsVtOI8OmN8+ZTxCm1Vd5pcZXiCoH+IBHjzFl625XgS9xGrox3sCz1GaSPAL8sd3z9EmlTyM=
