sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: m2JBfEz/ciHTLEocBEqoyDJ+N2xeyaGHr/MdSj2iZtVHyfYGH2CkAgvYaoZpeb3p2JnMw26c73h6JGjgjIh2M97KPDF1cXTSRS/8XiifrjIU7fgzB5TNU1/X8Ce/4ZaF5zF539NRAVINIHYihPcNNMDH9LHj7vcqZ5V2KPY5NJe/SELj6PVj1F+uwyceVOFPd4TwtqYPyH+rjrLD/ULrtv/73+PMLhOpUffgSF5WlVk6M+mA96ynIfbr+8kxYar/m0DnVEuSq+/7dH50iekpgMcNYpQnVlm4+yfYAjvuMmt6nRQwwj/o6R+cV0+2yBGmWomFIb2FBS4y2DvmDbg/zHhUYNxoUkaV1Bft6Hi4FnVZueS5cPjB6Id3kJi0N0MGJMiHk2hqJ0CVGYemLO+dzSfsOz2B7Y85HqmljIdyG2FOgTerOpfk4t3MbybXsKT45q5Yto0AjSw4npZj90GKAITsHPTaC2WIPy5o59UhsIhCBQXmAHAtd0e3Y9lWwTotTGjhsPr1Lb/r5vu7plW+Eg4wWaP08ZMUE9DnrwVaLqo+bXG3F+A3N7SS2ngL7iQ3xuLI58X063ejFLSDjspkOwO+LSFZ4W79TJZtL3zTO2h1NWLAQ5OhNtAkjaHQNVEI3/zLp5J91dDjsIJTrIWA6TaL8r6ZpmDtTL+tvx3qAgY=
  - secure: g16gbgRU58hg4pPiGJiRizBEH87yqEJMZwDDxtARbvClqDwyzH2e6Z+NGg33UKJNQcvd0gi7ag1RgxB4q3VAKvA3XkFImoc0VVS1tvWf9hjR2ft5VYlhF4Ec8KW7Av8wVHCwDTzK5MitNH7b+7/lKl79nSey6aEptGTgScSgINKhNiPhHVifq9+BMnXEgBp67fFunhPHgNbBJL8NiwQvQmiy7ZEgacYGCGqmYOj+uTnNcfPppy5w8lPHrnS9s/HPfl1dnsi4StA3KagY/nQUsr+6msAjuzl+AMkRy29OnFHQDtEAjsTQrkBpg+OFbYNPStwPtFlMdVckqjXABvlBJQhC4lUbnVXly1tQe9yJ71KlZWQ9lTSdWtmgrzMonFVNa1thPiPseK4Jc2nNqCwuVJZDrSJxV2Eit6lMwjvQHDRS6Quvzf5CCT2B4MNkGcnS8DwYfF08d/s+59kq9bwQjYu9e3wnFTsYrxhSy4oQCJCXfPEYzfYFaPSX18Pz8kLfdm/nWFcpNQ+EOoTKoVtt2it6/F4zXrIPyF8BAdlQVAaNz+4raCqb3Sv+RPOLEQUztq84U+huwAVSQqUBrHz6l+ZNcLQ0ekpUPDJAsVtOI8OmN8+ZTxCm1Vd5pcZXiCoH+IBHjzFl625XgS9xGrox3sCz1GaSPAL8sd3z9EmlTyM=
  - secure: QF+3X4NYH/ffYJ/gtDOqsTe5P3HZmSg/lfLOTu3rXCx8mK0Ea4I9afqmNseYt7WON1DWU7+yxMNFn1n0Jqp8DuVE89snHCUS2BzCnr3pm6Ge0fZXulIbKj93P02dOpGgqkN637+2wl7YlC+/996MDgiQMvJNa0r4s4qhmrFwXKCf9qjpbdkoslCyYWjbl76IEtEStkuqq6JFJAYHvdozVe+NZxeMqWHRXm0etCpz5H9r+kVXyEbKkB2w87E+ym7JuK6LT4bKp3zbp7alwcJjBuBhEf/567RMQVrTqjrViuanPQhOFHw3f5PnPUhd+SDYyFx5Drrow6sXyLykx3Z3zs8zImwjO5k5GB/nQZ4hCGM81yztHqHjlTlcG7aCc0OHhw6p4pAbnpuwk/KtdNjIhTonuzfPmhi/n6JHiOGkHWmX+kaNZtnkOf9WbMQZX4APHqNEAsIxFa7TPmGvEIwzHGi44xLHwdV/QeBCb+SDVJ0uHcZylLouvH92c/EF1vYFBygX/BcYveLkS3W8Ra80oxv/zO6iVCUfXZUQMF8msvpuV7O24t3rCaqa+0ODINFF/+uc5GaOUEc8kLHavDxtiigEcNrE0HSaTYhvPtoLavfDQkG6dX6xCRSBaMWe8ZHFWm4VoY1dZ5k0b1n+cZ50HdxrG85n1F5ApqNxfflaBZc=
